name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 60
        days-before-close: 7
        stale-issue-message: 'stale issue, closing for inactivity'
        stale-pr-message: 'stale pull request, closing for inactivity'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
